# Generated by Django 3.2.5 on 2021-07-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='user',
            field=models.CharField(default='', max_length=200),
        ),
    ]
